name: Create PR to main 

on:
  pull_request:
    branches: [ develop ]

jobs:
  deploy:
    name: Create PR to main branch 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Check PR type
      id: pr_type
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        # echo "${GITHUB_REF#refs/heads/}"
        # echo "$GITHUB_CONTEXT"
        echo "${{ github.head_ref }}"
        echo "${{ github.base_ref }}"
