name: Create PR to main 

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    name: Create PR to main branch 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Echo var
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "${GITHUB_REF#refs/heads/}"
        echo "$GITHUB_CONTEXT"
