name: Create PR to main 

on:
  pull_request:
    branches: [ develop ]

jobs:
  deploy:
    name: Create PR to main branch 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Output target branch 
      id: target_branch
      run: |
        # echo "${GITHUB_REF#refs/heads/}"
        # echo "$GITHUB_CONTEXT"
        echo "::set-output name=head::${{ github.head_ref }}"
        # echo "${{ github.base_ref }}"
    - name: Get branching type
      uses: jungwinter/split@v1
      id: split
      with:
        msg: ${{ steps.target_branch.outputs.head }}
        separator: '/'
    - name: Echoing
      run: echo "${{ steps.split.output._0  }}"
