name: Deploy 

on:
  push:
    branches: [ main, develop ]

deploy:
  name: Deploy to cloud
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v1
  - name: Setup PHP
    uses: shivammathur/setup-php@master
    with:
      php-version: '8.0'
  - name: Deploy
    uses: deployphp/action@master
    with:
      private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      ssh-config: ${{ secrets.SSH_CONFIG }}
      dep: deploy ${{ secrets.APP_ENV  }} -v
